### PR TITLE
contracts/tests: Fix flaky SIWE and gas cost

### LINKED ISSUE #443: Fix SIWE intermittent test issue
Fails here: https://github.com/oasisprotocol/sapphire-paratime/blob/a4beb2acfcb993af66299022b5db2ba984908f8d/contracts/test/auth.ts#L167

If the block takes too much time to be mined, then the last block timestamp is still considered and the bearer is not expired yet. Fix the test so that it waits for the block to be mined with the timestamp greater than `expiration`.

### PR DESCRIPTION
**Pull request by matevz**
Fixes #443 by waiting for the block with sufficiently new timestamp instead of fixed time.
Another workaround for #337.

### CODE REVIEW

File: contracts/test/auth.ts [hunk 1]
```diff
@@ -160,10 +160,15 @@ describe('Auth', function () {
       siweStr4,
       await erc191sign(siweStr4, account),
     );
-    // Wait until the next second after expiration
-    await delay(expiration.getTime() - Date.now() + 1000);
-    const tx = await siweAuthTests.doNothing();
-    await tx.wait();
+    // Wait until the block time is greater than the expiration date
+    await new Promise<void>((resolve, reject) => {
```
Comment (aefhm) [inline contracts/test/auth.ts:164]: (non-blocking) This might be a good helper/util function.

**Review by aefhm — APPROVED** [review]

**Review by CedarMist — APPROVED** [review]
